apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: second
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: second
  template:
    metadata:
      labels:
        app: second
    spec:
      containers:
        - name: second-flask
          image: erikmkrtchyan82/my_backend:2
