apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: second
  template:
    metadata:
      labels:
        app: second
    spec:
      containers:
        - name: second-flask
          image: erikmkrtchyan82/my_backend:4
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /app/data/
              name: text-volume
      volumes:
        - name: text-volume
          persistentVolumeClaim:
            claimName: host-pvc